#install.packages("dplyr", lib="~/Rpackages/")
#install.packages("DBI", lib="~/Rpackages/")
#install.packages("lubridate",lib="~/Rpackages/")
#install.packages("stringr", lib="~/Rpackages/")
#install.packages("ggplot2", lib="~/Rpackages/")
#install.packages("chron", lib="~/Rpackages/")           
#install.packages("hms", lib="~/Rpackages/")  
#install.packages("ggrepel",lib="~/Rpackages/")  
#install.packages("tidyr",lib="~/Rpackages/")  
#install.packages("openssl", lib="~/Rpackages/")  
#install.packages("httr", lib="~/Rpackages/")  
#install.packages("rvest", lib="~/Rpackages/")  
#install.packages("tidyverse", lib="~/Rpackages/")  
#install.packages("RColorBrewer", lib="~/Rpackages/")  
#install.packages("echarts4r", lib="~/Rpackages/")  
#install.packages("remotes", lib="~/Rpackages/")
#remotes::install_github("JohnCoene/echarts4r.assets")  
#install.packages("grid", lib="~/Rpackages/")  
#install.packages("cowplot", lib="~/Rpackages/")  
#install.packages("magick", lib="~/Rpackages/")  
#install.packages("RPostgres", lib="~/Rpackages/")  
install.packages("naniar", lib="~/Rpackages/")  

